name: scott
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - argon2-cffi=20.1.0
  - async_generator=1.10
  - attrs=20.3.0
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.3
  - bleach=3.3.0
  - brotlipy=0.7.0
  - ca-certificates=2020.12.5
  - certifi=2020.12.5
  - cffi=1.14.5
  - chardet=4.0.0
  - click=7.1.2
  - cryptography=3.4.7
  - cycler=0.10.0
  - dataclasses=0.8
  - dbus=1.13.6
  - decorator=5.0.5
  - defusedxml=0.7.1
  - descartes=1.1.0
  - entrypoints=0.3
  - expat=2.3.0
  - filelock=3.0.12
  - fontconfig=2.13.1
  - freetype=2.10.4
  - future=0.18.2
  - gettext=0.19.8.1
  - glib=2.68.0
  - glib-tools=2.68.0
  - gst-plugins-base=1.18.4
  - gstreamer=1.18.4
  - icu=68.1
  - idna=2.10
  - importlib-metadata=3.10.0
  - ipykernel=5.5.3
  - ipython=7.22.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.6.3
  - jedi=0.18.0
  - jinja2=2.11.3
  - joblib=1.0.1
  - jpeg=9d
  - jsonschema=3.2.0
  - jupyter=1.0.0
  - jupyter_client=6.1.12
  - jupyter_console=6.4.0
  - jupyter_core=4.7.1
  - jupyterlab_pygments=0.1.2
  - jupyterlab_widgets=1.0.0
  - kiwisolver=1.3.1
  - krb5=1.17.2
  - lcms2=2.12
  - ld_impl_linux-64=2.35.1
  - libblas=3.9.0
  - libcblas=3.9.0
  - libclang=11.1.0
  - libedit=3.1.20191231
  - libevent=2.1.10
  - libffi=3.3
  - libgcc-ng=9.3.0
  - libgfortran-ng=9.3.0
  - libgfortran5=9.3.0
  - libglib=2.68.0
  - libgomp=9.3.0
  - libiconv=1.16
  - liblapack=3.9.0
  - libllvm11=11.1.0
  - libopenblas=0.3.12
  - libpng=1.6.37
  - libpq=13.1
  - libprotobuf=3.15.7
  - libsodium=1.0.18
  - libstdcxx-ng=9.3.0
  - libtiff=4.2.0
  - libuuid=2.32.1
  - libwebp-base=1.2.0
  - libxcb=1.13
  - libxkbcommon=1.0.3
  - libxml2=2.9.10
  - llvm-openmp=11.1.0
  - lz4-c=1.9.3
  - markupsafe=1.1.1
  - matplotlib-base=3.4.1
  - mistune=0.8.4
  - mizani=0.7.3
  - mkl=2020.4
  - mysql-common=8.0.23
  - mysql-libs=8.0.23
  - nbclient=0.5.3
  - nbconvert=6.0.7
  - nbformat=5.1.3
  - ncurses=6.2
  - nest-asyncio=1.5.1
  - ninja=1.10.2
  - notebook=6.3.0
  - nspr=4.30
  - nss=3.63
  - numpy=1.20.2
  - olefile=0.46
  - openssl=1.1.1k
  - packaging=20.9
  - palettable=3.3.0
  - pandas=1.2.3
  - pandoc=2.12
  - pandocfilters=1.4.2
  - parso=0.8.2
  - patsy=0.5.1
  - pcre=8.44
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=8.2.0
  - pip=21.0.1
  - plotnine=0.8.0
  - prometheus_client=0.10.0
  - prompt-toolkit=3.0.18
  - prompt_toolkit=3.0.18
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pycparser=2.20
  - pygments=2.8.1
  - pyopenssl=20.0.1
  - pyparsing=2.4.7
  - pyqt=5.12.3
  - pyqt-impl=5.12.3
  - pyqt5-sip=4.19.18
  - pyqtchart=5.12
  - pyqtwebengine=5.12.1
  - pyrsistent=0.17.3
  - pysocks=1.7.1
  - python=3.9.2
  - python-dateutil=2.8.1
  - python_abi=3.9
  - pytorch=1.8.0
  - pytz=2021.1
  - pyzmq=22.0.3
  - qt=5.12.9
  - qtconsole=5.0.3
  - qtpy=1.9.0
  - readline=8.1
  - regex=2021.4.4
  - requests=2.25.1
  - sacremoses=0.0.43
  - scipy=1.6.2
  - send2trash=1.5.0
  - setuptools=52.0.0
  - six=1.15.0
  - sleef=3.5.1
  - sqlite=3.35.4
  - statsmodels=0.12.2
  - terminado=0.9.4
  - testpath=0.4.4
  - tk=8.6.10
  - tokenizers=0.10.1
  - tornado=6.1
  - tqdm=4.60.0
  - traitlets=5.0.5
  - transformers=4.4.2
  - typing_extensions=3.7.4.3
  - tzdata=2021a
  - urllib3=1.26.4
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - wheel=0.36.2
  - widgetsnbextension=3.5.1
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xz=5.2.5
  - zeromq=4.3.4
  - zipp=3.4.1
  - zlib=1.2.11
  - zstd=1.4.9
  - pip:
    - psaw==0.1.0
